AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: GraphQL server with AWS SAM

Resources:
  GraphQLFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs16.x
      Timeout: 120  # Set the timeout to 30 seconds
      Events:
        GraphQLAPI:
          Type: Api
          Properties:
            Path: /graphql
            Method: post