service: ai-my-personal-notes-api-graphql

provider:
  name: aws
  region: us-east-1
  httpApi:
    payload: "2.0"
    cors:
      allowedOrigins:
        - 'https://ai-my-personal-notes-ui.vercel.app'
        - 'http://localhost:3000'
      allowedMethods:
        - GET
        - OPTIONS
        - POST
        - PUT
        - DELETE
  lambdaHashingVersion: 20201221

functions:
  api:
    runtime: provided.al2
    package:
      artifact: dist/ai-my-personal-notes-api.zip
      individually: true
    handler: required-but-ignored
    events:
      - httpApi: "*"
